### ISSUE TITLE
Define Collection methods

### ISSUE THREAD

**Issue by rishidev** [ga4gh/data-repository-service-schemas#221]
Some points to discuss here:
How similar/different to object methods?
Distinguished endpoints for each or different?

**Comment by briandoconnor** [comment]
@susheel

**Comment by tetron** [comment]
From the perspective of CWL / WES, one thing that needs be clarified is how a DRS collection is intended to be materialized to a directory.  When a DRS collection is used as input to a workflow:

* How are filenames assigned?  Does the collection assign its own pathnames, or does it use the "name" field from the data object, or some combination of both?
* What happens if the "name" field of the data object is not defined (since it's currently labeled as optional)?
* What happens if there is a name collision?
* Can a single collection describe a file hierarchy (such as assigning pathnames that may include '/' to each file), or are subdirectories only represented as sub-collections?
** If sub-collections, how are they named?  What happens if there is a name collision between a data object and a collection?
* Can sub-collections be shared between collections?
* Does read access to a collection imply read access to data objects and/or sub-collections contained within?
* Can empty subdirectories be represented?

**Comment by delagoya** [comment]
Thanks @tetron, this is a good list to start with. Before we discuss each point, I want to confirm some agreements that were proposed during the Boston meeting:

1. That collections are immutable
2. Collections are not versioned
3. That you can have sub-collections
4. That a `GET` operation on a collection returns the immediate children (e.g. sub-collections require additional API operations to unroll).

**Comment by tetron** [comment]
1. yes
2. yes

3 & 4. that's what we agreed to, but I don't think we fully explored the alternatives.

**Comment by tetron** [comment]
This is the representation of a bundle in the current spec:

```
object_ids: [
  "drs://object1",
  "drs://object2",
  "drs://bundle3",
]
```

In order to materialize these into a directory, you would use the `name` field of each object or bundle.  In order for the collection to be immutable, the `name` field of each data object or bundle would also have to be immutable.  Which means if you want to rename a data object, you have to create a copy.

An alternate representation, where the collection assigns names to objects:

```
contents: {
  "/foo.bam": "drs://object1",
  "/foo.bai": "drs://object2",
  "/subdir/bar.bam": "drs://object3",
  "/subdir/bar.bai": "drs://object4"
}
```

Instead of sub-collections, a collection represents the entire directory tree.  This eliminates the possibility of circular dependencies by collections including themselves.  Fetching the collection record gives you more information up front about the contents of the collection, without having to fetch each object record separately.

**Comment by susheel** [comment]
@delagoya - Yes I think that was what was discussed in Boston.
1 & 2 are corollaries of each other.

Thanks, @tetron. I agree with the new representation. Yes that is what I was going for with the [example](https://docs.google.com/document/d/1cFcv5wdsfXI8SsEKtJcPqKTrxg5sCexLiyPy9kC-I5E/edit#bookmark=id.zhv6wciwz6d0) presented at the hackathon.

@tetron I agree about circular dependencies, but fully realising an entire collection, e.g. ENA Release 138 would result in over 1.5K files which would bloat up the `object list` and end up requiring pagination. Hence the proposal of defining sub-collections (3) and the possibility of unrolling the collection (4). 

@tetron Unrolling the subcollection using a query param, e.g. `?expand=true` will unroll the subcollection into the fully realised version.

**Comment by tetron** [comment]
Here's a third option, halfway between 1 & 2.  

```
contents: {
  "foo.bam": "drs://object1",
  "foo.bai": "drs://object2",
  "subdir": "drs://bundle3",
}
```

The collection assigns names but '/' is disallowed.  This still has the risk of circular includes, but (a) allows collections to assign their own names and (b) the collection record includes the names (without having to fetch each object separately to find out what the names are.)

**Comment by susheel** [comment]
@tetron I'm okay with that. So if we add the `?expand=true` query parameter will we end up with:

```yaml
contents: {
  "foo.bam": "drs://object1",
  "foo.bai": "drs://object2",
  "subdir/bar.bam": "drs://object3",
  "subdir/bar.bai": "drs://object4"
}
```

**Comment by susheel** [comment]
@tetron @delagoya If this is the only difference between data `objects` and `collections`. I'm keen to propose that `objects` will have an empty or null `contents` object. So you are able to have both `collections` and `objects` managed with the same data schema. Examples below:

```yaml
{
  id: 'ABC123'
  name: 'Object'
...
  contents: {}
...
}
```

```yaml
{
  id: 'XYZ890'
  name: 'Collection'
...
  contents: {
    "foo.bam": "drs://object1",
    "foo.bai": "drs://object2",
    "subdir/bar.bam": "drs://object3",
    "subdir/bar.bai": "drs://object4"
  }
...
}
```

Do you also want an additional flag in the combined schema e.g. `has_parts: true`? I'm not too keen on this as checking a flag and checking for not null is basically the same operation.

**Comment by tetron** [comment]
I don't think we've established whether a collection has access methods.  For some protocols (eg a site-specific nfs mount point) it might make sense, for others you have to grab individual objects.

**Comment by tetron** [comment]
A 4th option, you could also have a query parameter like "include_objects=true" to request that the object records are embedded in the collection record response.  Then you don't have to access object records separately, and you have the name, metadata (size, checksum etc) immediately available.

**Comment by delagoya** [comment]
Currently the `GET` on `drs://object1`  may contain a `name` field which is used to define the write target. I assume that in the case of a collection mapping, that the client ignores the individual object's name field in preference for the defined target of the collection. Correct? 

If so, to @susheel 's question about one data schema - there are possible schema clashes like above and I would like to keep them separate until we can work all the way through `collection` and `object` schema separately.

**Comment by geoffjentry** [comment]
I do not like the idea of embedding `/` in the middle of a name in order to create directory hierarchies. 

Wouldn't sub-collections handle the case where one wants to map the objects in a bundle into a POSIX-style FS w/ a directory hierarchy?

**Comment by susheel** [comment]
@delagoya Yes, it enables a collection owner to define the naming scheme of the objects sperate from the actual name of the object.

@geoffjentry Yes sub-collections should handle this as the original example. The forward-slash embedding will only occur when `?expand=true` is set. See example below:

**`GET drs://server.com/XYZ890`**
```yaml
{
  id: 'XYZ890'
  name: 'Collection'
  ...
  contents: {
    "foo.bam": "drs://object1",
    "foo.bai": "drs://object2",
    "subdir": "drs://collection1",
  }
  ...
}
```

**`GET drs://server.com/XYZ890?expand=true`**
```yaml
{
  id: 'XYZ890'
  name: 'Collection'
  ...
  contents: {
    "foo.bam": "drs://object1",
    "foo.bai": "drs://object2",
    "subdir/bar.bam": "drs://object3",
    "subdir/bar.bai": "drs://object4"
  }
  ...
}
```

**OR `GET drs://server.com/XYZ890?include_objects=true`** via @tetron 
```yaml
{
  id: 'XYZ890'
  name: 'Collection'
  ...
  contents: {
    "foo.bam": "drs://object1",
    "foo.bai": "drs://object2",
    "subdir": {
      "id": "collection1",
      "name": "subdir sub-collection",
      ...
      "contents": {
        "bar.bam": "drs://object3",
        "bar.bai": "drs://object4"
      }
      ...
    }
  }
  ...
}
```

My preference in order would be for `GET drs://server.com/XYZ890?expand=true` only for the sake of verbosity of the JSON response. However, I could be convinced to use  object embedding if the community wants to go in this direction.
