### ISSUE TITLE
Providing more metadata than access_url with GetAccessURLResponse?

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/data-repository-service-schemas#239]
This is a followup to our conversation on 20190311 and PR #236

See https://github.com/ga4gh/data-repository-service-schemas/pull/236#discussion_r264309098

`GetAccessURLResponse` just has `access_url` in the response.  Do we want to expand that to include more metadata in the future so DRS implementors can have the option to pass back more info than just a URL?  This would be needed if DRS implementors want to use DRS to hand back enough information to "get the bytes" for a variety of protocols beyond URLs/signed URLs.

**Comment by sarpera** [comment]
_Sort of related to this, adding `authorization_metadata` property to the items in `access_methods` array was also discussed in [this issue](https://github.com/ga4gh/data-repository-service-schemas/issues/47#issuecomment-467446033) as well._

**So far:**
`GetAccessURLResponse` via `/objects/<object_id>/access/<access_id>` is meant to return a ready-to-use byte access URL (e.g signed URL) already. Client is assumed to already have chosen an access method from the `access_methods` array and passed its `access_id` to above path to (optionally with auth token) get a url to bytes. 

**Suggestion:**
We can extend this for the cases like aspera, globus etc where `access_url` needs to be used along with some additional information like temp. credentials. I think it still doesn't defeat the original purpose; separating object metadata and access url that requires additional steps (signing, providing temp. credentials etc) to provide. 

Quoting from the the [discussion](https://github.com/ga4gh/data-repository-service-schemas/pull/236#discussion_r264309098) PR 236:

> In the previous response that came back we returned a URL along with system_metadata, user_metadata, and authorization_metadata. In the NIH Data Commons we needed the ability to provide more context about the URL to allow a user to make a request. 

Some examples how we can extend the original PR based on the use cases: 

Assumptions:
- Both `/objects/<id>` and  `/objects/<object_id>/access/<access_id>` are optionally behind some auth mechanism. We can easily add BasicAuth, 0Auth2 etc in `securityDefinitions` so that all standard auth mechanisms are allowed in DRS and calls to DRS are not ambiguous.
- Providing `access_url` may be costly and therefore unnecessary to provide each time an object method is requested
- Object metadata might be publicly accessible, but access url might require some auth

**Use Case 1**

- DRS contains an object that is stored in a private-access storage system
- Client doesn't have direct access to storage system; action required to get access (sign, get credentials/access token etc)
- A URL alone is enough to provide byte-access

Step 1: Client requests the object metadata via `/objects/<object_id>`:
```yaml
# ... 
"access_methods": [
    {
        "type": "s3",
        "access_id": "s3-1",
        "region": "us-east-1"     
    }, # ...
]
```

Step 2:  Client requests an access url via `/objects/<object_id>/access/<access_id>` providing auth token in the request header:
```yaml
{
    "access_url": "<byte-access-url>"
}
```

**Use Case 2**

- DRS contains an object that is stored in a private-access storage system
- Client has direct access to the storage system
- A URL alone is enough to provide byte-access

Step 1: Client requests the object metadata via `/objects/<object_id>` and consumes an `access_url` as is:
```yaml
# ... 
"access_methods": [
    {
        "type": "s3",
        "access_url": "s3://foo/bar.bam",
        "region": "us-east-1"     
    }, # ...
]
```


**Use Case 3**

- DRS contains an object that is stored in a private-access storage system
- Client doesn't have direct access to storage system; action required to get access (sign, get credentials/access token etc)
- A URL is NOT enough to provide byte-access

Step 1: Client requests the object metadata via `/objects/<object_id>`:
```yaml
# ... 
"access_methods": [
    {
        "type": "aspera",
        "access_id": "aspera-1"
    }, # ...
]
```

Step 2:  Client requests access url and additional information via `/objects/<object_id>/access/<access_id>` providing auth token in the request header:
```yaml
{
    "access_url": "<byte-access-url>",
    "access_credentials": {
        "foo": "bar"   
     } 
}
```

We can provide a structured vocabulary for the response in the schema.

**Use Case 4**

- DRS contains an object that is stored in a public-access storage system
- Client can access the object from any `access_url` from the metadata

Step 1: Client requests the object metadata via `/objects/<object_id>` and consumes an `access_url` as is:
```yaml
# ... 
"access_methods": [
    {
        "type": "s3",
        "access_url": "s3://foo/bar.bam",
        "region": "us-east-1"     
    }, # ...
]
```

How does it sound like? Are those use cases accurate?
