### ISSUE TITLE
Object size is defined as a string

### ISSUE THREAD

**Issue by ddietterich** [ga4gh/data-repository-service-schemas#251]
I just noticed that in `Object` the `size` field is define as:
```
     size:
        type: string
        format: int64
        description: |-
          The computed size in bytes.
```
swagger-codegen generates this as a string, ignoring the `format: int64`

I think this should be `type: integer`
